name: ugd6_1217
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  camera: ^0.10.5+5
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11
  mobile_scanner: ^3.5.1
  path: any
  path_provider: ^2.1.1
  qr_flutter: ^4.1.0
  flutter_local_notifications:

  sqflite: ^2.2.6
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

